//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Bicycle_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rent_a_Bicycle_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new bicycle.
        /// </summary>
        public static string addBicycle {
            get {
                return ResourceManager.GetString("addBicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent A Bicycle App.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle ID.
        /// </summary>
        public static string bicycleId {
            get {
                return ResourceManager.GetString("bicycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brandLeftSide {
            get {
                return ResourceManager.GetString("brandLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brandName {
            get {
                return ResourceManager.GetString("brandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string categoryLeftSide {
            get {
                return ResourceManager.GetString("categoryLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string continueButton {
            get {
                return ResourceManager.GetString("continueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer detail and Hiring Info:.
        /// </summary>
        public static string customerDetail {
            get {
                return ResourceManager.GetString("customerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string customerId {
            get {
                return ResourceManager.GetString("customerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete a bicycle.
        /// </summary>
        public static string deleteBicycle {
            get {
                return ResourceManager.GetString("deleteBicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string deposit {
            get {
                return ResourceManager.GetString("deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string gear {
            get {
                return ResourceManager.GetString("gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string gearLeftSide {
            get {
                return ResourceManager.GetString("gearLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire.
        /// </summary>
        public static string hireButton {
            get {
                return ResourceManager.GetString("hireButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring Date.
        /// </summary>
        public static string hiringDate {
            get {
                return ResourceManager.GetString("hiringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string paidAmount {
            get {
                return ResourceManager.GetString("paidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment detail:.
        /// </summary>
        public static string paymentDetail {
            get {
                return ResourceManager.GetString("paymentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent a Bicycle.
        /// </summary>
        public static string rentingABicycle {
            get {
                return ResourceManager.GetString("rentingABicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected bicycle detail:.
        /// </summary>
        public static string selectBicycle {
            get {
                return ResourceManager.GetString("selectBicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string sizeLeftSide {
            get {
                return ResourceManager.GetString("sizeLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string statusLeftSide {
            get {
                return ResourceManager.GetString("statusLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff/hour.
        /// </summary>
        public static string tariff {
            get {
                return ResourceManager.GetString("tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter bicycle info to filter list.
        /// </summary>
        public static string textFilter {
            get {
                return ResourceManager.GetString("textFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a bicycle to rent.
        /// </summary>
        public static string textSelect {
            get {
                return ResourceManager.GetString("textSelect", resourceCulture);
            }
        }
    }
}
